json.first student.first
json.last student.last
json.email student.email
json.phone student.phone
json.bio student.bio
json.linkedin student.linkedin
json.twitter student.twitter
json.website student.website
json.github student.github
json.photo student.photo
json.experiences student.experiences
json.educations student.educations
json.capstones student.capstones
json.skills student.skills
